package cn.teacy.wdd.controller;

import cn.teacy.wdd.common.constants.ProbeConstants;
import cn.teacy.wdd.dto.ProbeVo;
import cn.teacy.wdd.websocket.WsSessionManager;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpHeaders;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.io.*;
import java.util.List;
import java.util.Properties;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

@RestController
@RequestMapping("/api/probe")
@RequiredArgsConstructor
public class ProbeController {

    @Value("${wdd.probe.connect-key}")
    private String probeConnectKey;

    @Value("${wdd.probe.template-path}")
    private String templatePath;

    private final WsSessionManager sessionManager;

    @GetMapping("/list")
    public List<ProbeVo> listConnectedProbes() {
        return sessionManager.getProbeContexts().entrySet().stream()
                .map(entry -> new ProbeVo(
                        entry.getKey(), // ID
                        entry.getValue().getHostname(), // Hostname
                        entry.getValue().getSession().isOpen() ? "ONLINE" : "OFFLINE"
                ))
                .collect(Collectors.toList());
    }

    @GetMapping("/download")
    public void downloadProbe(@RequestParam(name = "type", defaultValue = "full") String type,
                              HttpServletResponse response) throws IOException {

        String templateName = "lite".equalsIgnoreCase(type) ? "probe-lite.zip" : "probe-full.zip";
        File templateFile = new File(templatePath, templateName);

        if (!templateFile.exists()) {
            response.sendError(HttpServletResponse.SC_NOT_FOUND, "Probe template not found: " + templateName);
            return;
        }

        // 获取当前请求的 Base URL，例如: http://localhost:8080 或 https://mydomain.com
        String baseUrl = ServletUriComponentsBuilder.fromCurrentContextPath().build().toUriString();

        String wsUrl = deriveWebSocketUrl(baseUrl);

        // 准备 probe.properties 内容
        Properties props = new Properties();
        props.setProperty(ProbeConstants.ConfigKeys.SERVER_URL, baseUrl);
        props.setProperty(ProbeConstants.ConfigKeys.WS_SERVER_URL, wsUrl);
        props.setProperty(ProbeConstants.ConfigKeys.PROBE_SECRET, probeConnectKey);
        props.setProperty(ProbeConstants.ConfigKeys.PROBE_ID, UUID.randomUUID().toString());

        ByteArrayOutputStream propsStream = new ByteArrayOutputStream();
        // 使用 store 存储，并补充注释
        props.store(propsStream, "Generated by WinDiagDoctor Server for " + baseUrl);
        byte[] propsBytes = propsStream.toByteArray();

        response.setContentType("application/zip");
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"WddProbe-" + type + ".zip\"");

        try (
                ZipInputStream zis = new ZipInputStream(new FileInputStream(templateFile));
                ZipOutputStream zos = new ZipOutputStream(response.getOutputStream())
        ) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                // 如果模板里已经有了 probe.properties，跳过它（我们要用新的覆盖）
                if (entry.getName().equals("probe.properties")) {
                    continue;
                }

                // 复制原文件
                zos.putNextEntry(new ZipEntry(entry.getName()));
                transfer(zis, zos);
                zos.closeEntry();
            }

            // 注入生成的 probe.properties
            ZipEntry propEntry = new ZipEntry("probe.properties");
            zos.putNextEntry(propEntry);
            zos.write(propsBytes);
            zos.closeEntry();

            zos.finish();
        }
    }

    private String deriveWebSocketUrl(String httpUrl) {
        String wsUrl;
        if (httpUrl.startsWith("https://")) {
            wsUrl = httpUrl.replaceFirst("https://", "wss://");
        } else {
            wsUrl = httpUrl.replaceFirst("http://", "ws://");
        }
        return wsUrl;
    }

    private void transfer(InputStream in, OutputStream out) throws IOException {
        byte[] buffer = new byte[8192];
        int len;
        while ((len = in.read(buffer)) > 0) {
            out.write(buffer, 0, len);
        }
    }

}
